src/accounts/urls.py
from django.urls import path, include
from .views import login_view, register_view, logout_view

app_name = 'accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    post_list,
    post_detail,
    post_new,
    post_edit,
    post_clap
)


app_name = 'blog'
urlpatterns = [
    path('',post_list, name='post_list'),
    path('post/<int:pk>/',post_detail, name='post_detail'),
    path('post/new/',post_new, name='post_new'),
    path('post/<int:pk>/edit/',post_edit, name='post_edit'),    
    path('post/<int:pk>/clap/',post_clap, name='post_clap'),    
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
]

src/accounts/models.py
from django.db import models

src/blog/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    PROGRAMMING = 'PR'
    SPORTS = 'SP'
    HEALTH = 'HE'
    MUSIC = 'MU'
    LIFE = 'LI'
    TRAVEL = 'TR'
    CATEGORY_CHOICES = [
        (PROGRAMMING, 'Programming'),
        (SPORTS, 'Sports'),
        (HEALTH, 'Health'),
        (MUSIC, 'Music'),
        (LIFE, 'Life'),
        (TRAVEL, 'Travel'),
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default=PROGRAMMING,
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=40)
    text = models.TextField()
    created_date = models.DateField(default=date.today)
    claps = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate, get_user_model


class RegisterForm(forms.Form):
    email = forms.EmailField()
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20)
    confirm_password = forms.CharField(max_length=20)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20)

    def check(self):
        pass 
        

src/blog/forms.py
from django import forms 
from .models import Post 


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
            'category',
            'title',
            'text'
        ]

src/accounts/views.py
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.shortcuts import (
    render, 
    redirect, 
    reverse, 
    HttpResponse)

from django.contrib.auth import (
    login, 
    logout, 
    authenticate, 
    get_user_model)



def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('name')
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            User.objects.create_user('john', 'lennon@thebeatles.com', 'johnpassword')
            username = 'john'
            password = 'johnpassword'
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('blog:post_list'))

    form = RegisterForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('blog:post_list'))
    form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return redirect(reverse('blog:post_list'))

src/blog/views.py
from .models import Post
from datetime import date
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

def post_list(request):
	posts = Post.objects.all()
	context = {
		'posts' : posts
	}
	return render(request,'blog/post_list.html',context)


def post_detail(request,pk):
	post = get_object_or_404(Post,pk=pk)
	context = {
		'post' : post
	}
	return render(request, 'blog/post_detail.html',context)


def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.created_date = date.today()
			post.save()
			return redirect('post_detail', pk=post.pk)
	else:		
		form = PostForm()
	context = {
		'form' : form
	}
	return render(request, 'blog/post_edit.html',context)


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    context = {
    	'form' : form
    }
    return render(request, 'blog/post_edit.html', context)


def post_clap(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.claps += 1
    post.save()
    return redirect(reverse('blog:post_detail', kwargs={'pk':pk}))

src/accounts/templates/accounts/base.html
{% load static %}
<html>

    <head>
        <title>Blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Roboto&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">

    </head>

    <body>
        {% block content %}
        {% endblock %}
    </body>   
</html>

src/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="login">
    </form>
{% endblock %}  

src/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="register">
    </form>
{% endblock %}  

src/blog/templates/blog/base.html
{% load static %}
<html>

    <head>
        <title>Blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Roboto&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">

    </head>

    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu">
                    Write New
                </a>
            {% endif %}
            <h1><a href="/">Blog</a></h1>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-6">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>   
</html>

src/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div class="post">        
        {% if user.is_authenticated %}
        	<a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}">edit post</span></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        <p>
            <button><a href="{%url 'blog:post_clap' pk=post.pk %}"><img src="{% static 'blog/images/clap.png' %}" width="20px" height="20px"></a></button>
             {{ post.claps }}
        </p>
    </div>
{% endblock %}  

src/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
	<h2>New Post</h2>
	<form method="POST" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">save</button>
	</form>
{% endblock %}

src/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load mathfilters %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                <p>{{ post.get_category_display }}</p>
            </div>
            
            <h2>
                <a href="{%url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
            </h2>
            <p>
                {{ post.text|truncatewords:30 }}
                <a href="{%url 'blog:post_detail' pk=post.pk %}">read more</a>
            </p>
            <p>By {{ post.author }}</p>
            <div class="date">
                <p>
                    {{ post.created_date }} . 
                    {{ post.text|wordcount|intdiv:256 }} 
                    min read
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}